#!/usr/bin/env bash

# TODO: what things should I set here, like pipefail and lastpipe and so forth?

# get the path to the script
if [ -z "$1" ]
then
  echo "badash: Missing argument: script to execute" >&2
  exit 1
fi
script_file="$1"
shift

# TODO: help argument to describe usage

# ensure the cache dir exists
script_cache="$HOME/.badash"
mkdir -p "$script_cache"

# generate a new script
generated_script="$script_cache/$(basename "$script_file")"
# first line in the file, so that bash will execute the script
echo "#!/usr/bin/env bash" > "$generated_script"

# read the script line by line
while IFS= read -r line
do
  echo "$line" >> "$generated_script"
done <"$script_file"

# make sure it is executable
chmod +x "$generated_script"

# execute the generated script
"$generated_script" "$@"

# TODO: catch/identify errors and print the line that they came from
# (in the original file)
