name: "CI"
on: [push, pull_request]
jobs:
  test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: bats test/
